# serverless.yml

service: graf-rent-acciones-lp
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: rent
  region: us-east-2
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_PORT: ${env:DB_PORT}
    DB_DATABASE: ${env:DB_DATABASE}
    TABLE_ACCIONES: ${env:TABLE_ACCIONES}

functions:
  app:
    handler: index.handler
    description: LTG19 - Obtiene el gráfico de Rentabilidad a largo plazo de Acciones desde los datos de AWS RDS.
    events:
      - httpApi: 
        cors: true
        method: GET
        path: /rent/